apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc1
  labels:
    name: jenkpvc1
spec:
  accessModes:
   - ReadWriteOnce
  resources:  
    requests:
      storage: 1Gi